### ISSUE TITLE
GPAD export from blazegraph not working with generated TTL

### ISSUE THREAD

**Issue by dustine32** [geneontology/gocamgen#15]
Loaded models generated from gocamgen somehow break the GPAD export function in minerva that drives the export in Noctua.

Last time GPAD export broke for my generated models it was with the SynGO models. The culprit there ended up being that I was using certain property that wasn't supported by minerva. I'll look up what the property was and see if it's in the gocamgen models.

**Comment by goodb** [comment]
Suspect this is related to #22

**Comment by dustine32** [comment]
So contributor on the evidence nodes is being filled with an empty string right now due to the data not being available through ontobio's GpadParser (https://github.com/biolink/ontobio/issues/288). But this still seems to fix the GPAD export.
