### ISSUE TITLE
fix ontology term URIs

### ISSUE THREAD

**Issue by goodb** [geneontology/gocamgen#22]
GO terms used in exported ttl 
use an identifier.org uri like http://identifiers.org/GO:0000302

they should always be using purls like 
http://purl.obolibrary.org/obo/GO_0000302

**Comment by goodb** [comment]
@kltm I'm making an assumption that the URIs we see in the Noctua-generated models are what we want to see.  e.g. http://www.wormbase.org/db/gene/gene?name=WBGene00004055  for a worm gene class (assuming in neo).  That correct right, we can't just use identifiers.org e.g. @dustine32 currently has @prefix WB: <http://identifiers.org/wormbase/>  which I think is wrong.

**Comment by kltm** [comment]
I'm not sure if this has happened; tagging @cmungall

**Comment by goodb** [comment]
Based on what is coming out of noctua (prod) not noctua-dev, the identifiers.org pattern seems correct for the gene products, e.g. http://identifiers.org/mgi/MGI:108078 .  But, definitely need to use the purls for ontology classes and relations.
