### ISSUE TITLE
Example GO CAMs for annotations to regulation terms

### ISSUE THREAD

**Issue by ukemi** [geneontology/gocamgen#23]
For an annotation of Gene A to 'regulation of X', the models need to be decomposed into a regulatory process and the process that is being regulated. So if a gene product is annotated to 'regulation of leukocyte differentiation' the annoton would look like:
MF enabled_by A, MF-part_of;causally upstream of etc-generic BP, generic BP-regulates-X.

For annotation extensions, when the relation is a property chain like regulates_o_relation-T then the annotation extension should be added to the regulated process X. So the annotation extension would be X-relation-T.

MGI | MGI:108078 | acts_upstream_of_or_within | GO:0042662 | MGI:MGI:3711603\|PMID:17462603 | ECO:0000316 | MGI:MGI:98956 | 20091104 | MGI | regulates_o_results_in_specification_of(CL:0000352)
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by ukemi** [comment]
One complication to this is that if  the GO term is 'regulation of X by BP2' then the generic BP above should be replaced by BP2.

**Comment by goodb** [comment]
Example of GPAD export from that model

Sfrp2 Mmus | involved_in | negative regulation of cell fate specification | PMID:17462603 | genetic interaction evidence used in manual assertion | MGI:MGI:98956 |   | 20190131 | GO_Central | negatively_regulates(cell fate specification) | contributor=http://orcid.org/0000-0002-7334-7852\|noctua-model-id=gomodel:5c4605cc00000315\|model-state=development
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by goodb** [comment]
@vanaukenk @kltm please add this and others like it to unified transform rules document.  https://docs.google.com/document/d/1AgkJqA4-V0HG0SaDiNO9ENTxaQC_1HwsmwyhyHhuxog/edit#heading=h.i4mj256scnr4 and its final wiki resting place..
