### ISSUE TITLE
CC annotations should just be part_of

### ISSUE THREAD

**Issue by ukemi** [geneontology/gocamgen#27]
For a cellular component annotation, the model should just indicate GP<>part_of<>CC, not GP<>enables<>MF<>coccurs_in<>CC.

See model

 gomodel:785e6d6b-fbda-4b41-9268-6493c8ee37a1

**Comment by goodb** [comment]
@ukemi why not follow the occurs_in structure ?

**Comment by goodb** [comment]
And where is the model you are referring to?  That id doesn't look like a normal noctua id.

**Comment by ukemi** [comment]
Because when a curator makes a CC annotation, in some cases all they know is that the GP is localized to the CC. They have expressed to us that they are not always confident that the GP functions in the CC. As the most conservative default we should simply make GP part_of CC. One caveat to this is the discussion at the hackathon about the use of a new default relation. I'm not sure we made a firm decision about that. 

The model is on the development server. I can get to it using the above id.

**Comment by vanaukenk** [comment]
Yes, that is the rationale: in 'conventional' annotation, curators sometimes captured localization even if it was not known (or even in some cases when it was known) that a gene product enabled its function in that location.
We are being conservative here in bringing in the CC annotations to, right now, just express these as GP 'part of' CC.
The proposal for the new relations, i.e. 'localizes to or part of' and 'localizes to', is still being discussed with the curators.

**Comment by vanaukenk** [comment]
Note that we also have annotations where curators have used 'colocalizes_with' for the relation between the GP and CC term.
I've added this to the [rules spreadsheet](https://docs.google.com/spreadsheets/d/1bpgF0FpnjbOzfH6bQXPP3ygRpme_MuP6-DOOMdTivu4/edit#gid=0)
For now, I think we will just have to import these annotations as is, although going forward it would be nice to remove as many of these as possible from the annotation sets.

**Comment by vanaukenk** [comment]
Update: note that in the course of importing the MOD annotations, we changed the 'default' gp2term relation for CC:

for non-protein-containing complex CC terms, the default relation is 'located in'
for protein-containing complex CC terms, the default relation in 'part of'
