### ISSUE TITLE
add an annotation to track gpad source line

### ISSUE THREAD

**Issue by goodb** [geneontology/gocamgen#28]
For each statement that gets generated from a line of GPAD, add an OWL annotation containing a String capturing the full GPAD line.  Something like:
`rdfs:comment "GPAD_ORIGIN: WB	WBGene00000816	part_of	GO:0005634	GO_REF:0000037	ECO:0000501	UniProtKB-KW:KW-0539		20180707	UniProt	" ` 

This can be attached to the evidence block.  It will be useful for debugging and can be removed once the importer is complete (or left as part of the provenance trail).

**Comment by dustine32** [comment]
Finally got this to work. Before I was adding `rdfs:comment` to both the axiom and evidence individual. Just needed it on the axiom.

**Comment by dustine32** [comment]
Oh yeah, forgot to show how it looks:
![image](https://user-images.githubusercontent.com/2678599/52892154-ddc93900-3144-11e9-9881-00d5b0cdca66.png)
