### ISSUE TITLE
Imports need to be filtered by Assigned_by field

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/gocamgen#30]
For importing the WB annotations, we will need to first filter the gpad file using the 'WB' value in the Assigned_by field.

In the current import on noctua-dev, it looks like we also have manual annotations from other groups, for example, Assigned_by 'UniProt'.

**Comment by vanaukenk** [comment]
This looks to be fixed for WB.  Thx.
@ukemi - if this is also fine for MGI, then we can close this ticket.

**Comment by ukemi** [comment]
I think this works for us now too. I have Mary doing something a bit more automated, but the spot checks and recent changes at MGI all make sense.
