### ISSUE TITLE
Merged triples creating "orphaned" axioms/evidence

### ISSUE THREAD

**Issue by dustine32** [geneontology/gocamgen#34]
I spotted this in a MGI model for two annotations to the same ID and term:
![image](https://user-images.githubusercontent.com/2678599/54165167-d08a2c00-441c-11e9-8fdd-556dfbae7a07.png)
MGI:MGI:87859 to GO:0004713

I'm suspecting it's due to emitting evidence URI, dates, comments triples to an axiom for each new evidence rather than appending the evidence URI to the LEGO:evidence property of the single axiom. May the solution is similar to this?
```
[ rdf:type owl:Axiom ;
   owl:annotatedSource <http://model.geneontology.org/66ab4fd6-68b2-4e3c-aa19-88199eca825e/86ed125d-a654-426d-aaa6-48a30f750a95> ;
   owl:annotatedProperty <http://purl.obolibrary.org/obo/RO_0002333> ;
   owl:annotatedTarget <http://model.geneontology.org/66ab4fd6-68b2-4e3c-aa19-88199eca825e/e46feaf1-2984-43d0-a3ed-d292cead6ef0> ;
   <http://geneontology.org/lego/evidence> <http://model.geneontology.org/66ab4fd6-68b2-4e3c-aa19-88199eca825e/61d635f0-2397-4c0c-908a-740637d14b9d> , <http://model.geneontology.org/66ab4fd6-68b2-4e3c-aa19-88199eca825e/949d06a6-3355-4614-b8a3-2dbdef877c1f> ;
   <http://purl.org/dc/elements/1.1/contributor> "http://orcid.org/0000-0002-6659-0416" ;
   <http://purl.org/dc/elements/1.1/date> "2014-07-14" ;
   rdfs:comment "MGI MGI:87859 enables GO:0004713 MGI:MGI:2384444|PMID:12167702 ECO:0000315   20140714 MGI has_direct_input(MGI:MGI:104741)"
 ] .
```

Specifically the line:
```
<http://geneontology.org/lego/evidence> <http://model.geneontology.org/66ab4fd6-68b2-4e3c-aa19-88199eca825e/61d635f0-2397-4c0c-908a-740637d14b9d> , <http://model.geneontology.org/66ab4fd6-68b2-4e3c-aa19-88199eca825e/949d06a6-3355-4614-b8a3-2dbdef877c1f> ;
```

**Comment by dustine32** [comment]
Well, I do notice that there are some axioms in this OWL that already use my proposed solution:
```
[ rdf:type owl:Axiom ;
   owl:annotatedSource <http://model.geneontology.org/66ab4fd6-68b2-4e3c-aa19-88199eca825e/91d1e1f5-8d54-4f09-aa47-f2e3dd12c672> ;
   owl:annotatedProperty <http://purl.obolibrary.org/obo/RO_0002333> ;
   owl:annotatedTarget <http://model.geneontology.org/66ab4fd6-68b2-4e3c-aa19-88199eca825e/1e478989-604a-4cfb-ac5f-78324e0ad69d> ;
   <http://geneontology.org/lego/evidence> <http://model.geneontology.org/66ab4fd6-68b2-4e3c-aa19-88199eca825e/27f7ae19-d188-4f82-ad55-3994933c147c> ,
                                           <http://model.geneontology.org/66ab4fd6-68b2-4e3c-aa19-88199eca825e/89c7879d-9f93-4a1c-9f90-318b2e30c05e> ;
   <http://purl.org/dc/elements/1.1/contributor> "http://orcid.org/0000-0002-6659-0416" ;
   <http://purl.org/dc/elements/1.1/date> "2012-10-04" ,
                                          "2012-10-05" ;
   rdfs:comment "MGI MGI:87859 enables GO:0005515 MGI:MGI:1099567|PMID:8861907 ECO:0000353 UniProtKB:Q03173  20121005 MGI" ,
                "MGI MGI:87859 enables GO:0005515 MGI:MGI:1349267|PMID:10567556 ECO:0000353 UniProtKB:Q9QZK7  20121004 MGI"
 ] .
```
For MGI:MGI:87859 to GO:0005515 annotations.

So something else must be going on to explode out the evidence for the MGI:MGI:87859-to-GO:0004713 associations into multiple axioms.

**Comment by goodb** [comment]
@dustine32 I've experienced this a lot in my development.  Somehow you ended up with an evidence instance that is not connected to anything else.  When I have done this to myself, it has usually been related to trying and failing to delete a relationship that I have added to the model.  Delete is a pain as you need to cascade it through all the evidence nodes etc.  If you send me a full model that contains the problem maybe I can help diagnose.

**Comment by dustine32** [comment]
Thanks @goodb ! Here's the [model](http://68.181.125.171:8910/editor/graph/gomodel:66ab4fd6-68b2-4e3c-aa19-88199eca825e) for MGI:MGI:87859. I can email you the original TTL file if you're interested.

As far as I know, my code shouldn't be deleting relations when building the graph that gets submitted to rdflib (builds the TTL). I try to first search and reuse axioms and create if they don't exist. But I think my `add_evidence` code is redundantly emitting the axiom for some of these evidences. I probably need to break some of the emitting responsibility out of this `add_evidence` function. Though I haven't yet followed this through the debugger.

**Comment by goodb** [comment]
I notice there are bunch of assertions with no evidence.  Perhaps evidence nodes are getting created but not linked up?  e.g. 

gomodel:66ab4fd6-68b2-4e3c-aa19-88199eca825e/9e18e9f5-67b0-4fd0-8165-be66607f7acc / RO:0002333 / gomodel:66ab4fd6-68b2-4e3c-aa19-88199eca825e/e46feaf1-2984-43d0-a3ed-d292cead6ef0

**Comment by dustine32** [comment]
Aha! Thanks @goodb this triple pointed me to the likely weirdness going on with my extension code. I just switched from reusing the extension logic from my PomBase models to something much simpler and this problem appears to have gone away.

**Comment by dustine32** [comment]
Should be fixed by https://github.com/geneontology/gocamgen/commit/e6c058968b4754949ca82f5fa764c0b5a363ced0
