### ISSUE TITLE
Include annotations using high throughput (HTP) manual assertion evidence codes in import

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/gocamgen#35]
For MOD imports, we also want to include annotations that use one of the 'high throughput evidence used in manual assertion' evidence codes.  These are:

ECO:0006056 | High throughput evidence used in manual assertion | HTP

ECO:0007001 | High throughput mutant phenotype evidence used in manual assertion | HMP

ECO:0007003 | High throughput genetic interaction evidence used in manual assertion | HGI

ECO:0007005 | High throughput direct assay evidence used in manual assertion | HDA

ECO:0007007 | High throughput expression pattern evidence used in manual assertion | HEP

Thx.

**Comment by dustine32** [comment]
Just checked for some HT examples that made it into the last noctua-dev [load](https://github.com/geneontology/noctua-models/pull/113). There's one here for WB:WBGene00000114:
http://noctua-dev.berkeleybop.org/editor/graph/gomodel:2dbd83ae-a6c4-4cd3-8a45-d466f1af0239

Showing source lines in comment:
![image](https://user-images.githubusercontent.com/2678599/54778011-dc21e380-4bd0-11e9-80b3-45363599ebcf.png)

Also, as a side-note, a few of these codes don't seem to appear in the source `wb.gpad` file:
```
$ grep ECO:0006056 wb.gpad | wc -l
       0
$ grep ECO:0007001 wb.gpad | wc -l
       0
$ grep ECO:0007003 wb.gpad | wc -l
       0
$ grep ECO:0007005 wb.gpad | wc -l
     387
$ grep ECO:0007007 wb.gpad | wc -l
     185
```

**Comment by vanaukenk** [comment]
@dustine32 - those numbers fit with what I see in our source GPAD, although there are a few more ECO:0007005, presumably from UniProt and we are not importing those.

I'll go ahead and close this ticket as I think we're good wrt the HTP evidence codes.  Thx.
