### ISSUE TITLE
GP acts_upstream_of_or_within BP -> root MF enabled by GP causally_upstream_of_or_within BP

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/gocamgen#38]
Gene products annotated to BP terms with the 'acts upstream of' or 'acts upstream of or within' relation should be imported as, for example:

GP <- enabled_by [root MF] -> causally_upstream_of BP

The equivalent model would be used for 'acts upstream of or within' except that the relation between the root MF and the BP would be 'causally upstream of or within'.

See  http://noctua-dev.berkeleybop.org/editor/graph/gomodel:4187773d-e2b6-4235-895c-40436435d60d

for how they are currently imported.

**Comment by ukemi** [comment]
The rules for BP are lines 9-16 of the spreadsheet. I now see that they are not implemented. Sorry for the false alarm.

**Comment by dustine32** [comment]
@ukemi @vanaukenk I have a test model loaded on my server, which is now finally accessible outside USC!
http://68.181.46.18:8910/editor/graph/gomodel:9b110628-d19d-462b-8169-bbf40c0cf187

This has three examples of "acts_upstream_of_or_within" being translated. I'll find some more examples of the positive and negative effect relations being translated. If those also look good, I can run the latest code on the whole lot of WB/MGI and PR them to noctua-dev.

**Comment by goodb** [comment]
HI @dustine32 just curious why http://identifiers.org/mgi/MGI:1206591 isn't being shown as Bik Mmus ?  The URI looks right in the OWL, so its probably not important for this issue.  I'm guessing maybe you didn't load neo in your dev server (because it takes a while) ?  (Can't remember if its neo or if its GOLR or something that grabs those labels.)

**Comment by dustine32** [comment]
Yep, correct, it's NEO not being loaded on my server that's preventing the labels from displaying. I can probably switch back to loading it since it doesn't really take a crazy amount of time to load.

**Comment by vanaukenk** [comment]
@dustine32 - the test model looks good.  Let's run the latest code on the WB and MGI annotation sets and see how they look!

Thx.

**Comment by dustine32** [comment]
@vanaukenk Latest set of WB/MGI models are loaded into noctua-dev. [This PR](https://github.com/geneontology/noctua-models/pull/116) has some stats on source files used.

Here's our example model (MGI:MGI:1206591) from above in noctua-dev:
http://noctua-dev.berkeleybop.org/editor/graph/gomodel:6ac737bd-6178-4867-8e4a-4de91c02a366
