### ISSUE TITLE
WB:WBGene00006498 model is missing all BP annotations from WB

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/gocamgen#41]
WB:WBGene00006498 (ten-1) should have 17 Biological Process annotations associated with it, but right now, I only see the two CC annotations.

http://noctua-dev.berkeleybop.org/editor/graph/gomodel:e2ebe743-1704-4716-9a86-a9aa6ca7306f

Some examples of missing annotation lines from the snapshot GPAD:

WB	WBGene00006498	involved_in	GO:0007276	PMID:15936327|WB_REF:WBPaper00025239	ECO:0000315			20090108	WB

WB	WBGene00006498	involved_in	GO:0008406	PMID:18632986|WB_REF:WBPaper00032026	ECO:0000315	WB:WBVar00091925		20090108	WB

WB	WBGene00006498	involved_in	GO:0009792	PMID:18632986|WB_REF:WBPaper00032026	ECO:0000316	WB:WBGene00000961		20090108	WB	
	
WB	WBGene00006498	involved_in	GO:0009792	PMID:18632986|WB_REF:WBPaper00032026	ECO:0000316	WB:WBGene00001328		20090108	WB		

WB	WBGene00006498	involved_in	GO:0009792	PMID:18632986|WB_REF:WBPaper00032026	ECO:0000316	WB:WBGene00002081		20090108	WB	
	
WB	WBGene00006498	involved_in	GO:0009792	PMID:18632986|WB_REF:WBPaper00032026	ECO:0000316	WB:WBGene00003738		20090108	WB	
	
WB	WBGene00006498	involved_in	GO:0009792	PMID:22938866|WB_REF:WBPaper00041503	ECO:0000316	WB:WBGene00002251		20121022	WB	
	
WB	WBGene00006498	involved_in	GO:0009792	PMID:22938866|WB_REF:WBPaper00041503	ECO:0000315	WB:WBVar00091925		20121022	WB	
	
WB	WBGene00006498	involved_in	GO:0010172	PMID:21795395|WB_REF:WBPaper00039988	ECO:0000316	WB:WBGene00001077		20111103	WB

**Comment by vanaukenk** [comment]
This seems to be a bit more prevalent - lat-1 (WB:WBGene00002251) is also missing all of its WB BP annotations.

**Comment by dustine32** [comment]
@vanaukenk Yep, this was a stupid mistake I made that was easy to track down through a quick debugging. The fixed models for WB:WBGene00006498 and WB:WBGene00002251 are on my server and I'll send a link once its accessible outside USC.

**Comment by dustine32** [comment]
These are ready to check out in noctua-dev:
WB:WBGene00006498 - http://noctua-dev.berkeleybop.org/editor/graph/gomodel:63a20a53-3261-4146-be50-6048ec663bee
WB:WBGene00002251 - http://noctua-dev.berkeleybop.org/editor/graph/gomodel:1c39abb7-74bf-4b61-863a-8f39cceae819

**Comment by vanaukenk** [comment]
@dustine32 
I've looked at a number of C. elegans genes and all of the expected biological process annotations are present, so I'll go ahead and close this ticket.  Thx.
