### ISSUE TITLE
'With' field info missing from IMP annotation

### ISSUE THREAD

**Issue by ukemi** [geneontology/gocamgen#48]
The gene  MGI:1859682 is annotated to GO:0008520 with an IMP evidence code. The original annotation has an allele value in the with field (MGI:2180333). The 'with' field is missing from the model on noctua-dev.

Original annotation in GPAD:
MGI	MGI:1859682	enables	GO:0008520	MGI:MGI:2178849|PMID:11984597	ECO:0000315	MGI:MGI:2180333		20030212	MGI

**Comment by vanaukenk** [comment]
@ukemi  - I don't think the imports of With/From has been implemented yet.
@dustine32 - please correct me if I'm wrong.

**Comment by ukemi** [comment]
OK. Sorry. I'm behind the curve. Feel free to close.

**Comment by dustine32** [comment]
Right, I haven't yet translated the with/from values yet. Just determined how to handle this field when grouping annotations. But while we're here @ukemi , you'd like this "MGI:MGI:2180333" value to go into the evidence here?
![image](https://user-images.githubusercontent.com/2678599/56989516-7cabe180-6b47-11e9-95b9-fc41c72c3382.png)


If yes, then this is probably easy enough to add, so I say we just keep this ticket open until it is added?

**Comment by ukemi** [comment]
Yes. It would go in the second field if I were adding evidence by hand.

'If appropriate enter with/from value (must be in form of Prefix:ID)

**Comment by dustine32** [comment]
Hi @ukemi I believe I have this model generated to correctly add the with/from value. You can check it out here:
http://68.181.46.18:8910/editor/graph/gomodel:b327aa6b-4362-4acb-827a-a118ba9ba533

**Comment by ukemi** [comment]
Hi @dustine32 
Should I look at some more?

**Comment by dustine32** [comment]
@ukemi @vanaukenk Yep, I also figured out a lot of the with/from translation, including for protein binding and descendants. The models on my test server dated today should have the latest updates.

I'm generating the new batch of all models with this code right now and can push them to noctua-dev if you guys think they look good.

**Comment by dustine32** [comment]
Specifically:
* Non-protein binding case w/ commas (MGI:MGI:87859 to GO:0004713):
http://68.181.46.18:8910/editor/graph/gomodel:8ae5b436-06a6-466b-8f92-d5c440d77d7d
* Protein binding case (WB:WBGene00000018 to GO:0005515):
http://68.181.46.18:8910/editor/graph/gomodel:42f4459e-658f-4cbf-90e8-c850ddaffa7d
* Protein binding descendant case (WB:WBGene00000099 to GO:0019894):
http://68.181.46.18:8910/editor/graph/gomodel:0921df78-c197-487e-b8f9-4224a9989b5f
* Protein binding w/ pipes (WB:WBGene00002173 to GO:0017022):
http://68.181.46.18:8910/editor/graph/gomodel:8955f23c-4519-4eb1-b19f-64c5f5eba7da

All these URLs _should_ stay persistent.

**Comment by vanaukenk** [comment]
@dustine32 
The three protein binding examples above from WB all look correct to me.  Awesome job!  Thanks!

**Comment by ukemi** [comment]
Hi @dustine32 . It looks like the comma case is not working. I thought we had decided these would simply be put in as string literals when the term was not a protein binding term. I would have expected to see a single evidence statement with the comma-separated with value.

![image](https://user-images.githubusercontent.com/11067494/57324789-98c6fa00-70d6-11e9-9611-8f56db578e4f.png)

**Comment by dustine32** [comment]
@ukemi Well, crap. Sorry, I must've confused having to create separate evidence for something else with this. This is an easy thing to fix. I'll try getting a test model regenerated soon. Good catch!

**Comment by dustine32** [comment]
@ukemi Got the comma back:
http://68.181.46.18:8910/editor/graph/gomodel:edfc5dcd-e195-4af9-96d1-71d3fe072440
![image](https://user-images.githubusercontent.com/2678599/57347891-d8a6d500-7108-11e9-91fd-e0326625450f.png)
