### ISSUE TITLE
change has_direct_input to has_input for imported BP and MF annotations

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/gocamgen#49]
As part of the input code, we want to change annotation extensions that use 'has direct input' to 'has input'.

**Comment by dustine32** [comment]
This should be easy to handle. I have the "relation string"-to-RO lookup [hard-coded here](https://github.com/geneontology/gocamgen/blob/144fb3ddfe0ea9fa129bc9dc3b65abf2fe6f9844/gocamgen/gocamgen.py#L63) for now. It assigns RO:0002233 (has input) to any "has_direct_input" extension relations.

Also, here's a test example for WB:WBGene00000407 enables [GO:0004672] protein kinase activity has_direct_input(WB:WBGene00002999):
http://68.181.46.18:8910/editor/graph/gomodel:ed3b9d3d-730d-4f33-ae20-7cdd96b29736

**Comment by vanaukenk** [comment]
Thanks @dustine32 
The example above for WB:WBGene00000407 looks correct to me (both wrt the has_input and combined evidence).

**Comment by dustine32** [comment]
The latest model push to noctua-dev shows this same WB:WBGene00000407 model correctly translating `has_direct_input` to `has_input`:
http://noctua-dev.berkeleybop.org/editor/graph/gomodel:3e7e19aa-9871-4e19-82bd-63fb472fe714
