### ISSUE TITLE
add taxon metadata for each model

### ISSUE THREAD

**Issue by goodb** [geneontology/gocamgen#80]
To get the Minerva search API working with taxon information https://github.com/geneontology/minerva/issues/290 , we need to add it to models that are coming in.  This can be done in batch updates later, but might as well just add it in the beginning so we get it right..  Subject is the model itself like when you add a title, predicate is https://w3id.org/biolink/vocab/in_taxon and object is a taxon URI like: http://purl.obolibrary.org/obo/NCBITaxon_9606 (that would be human).  

Example ttl for model metadata now looks something like this.  

```
<http://model.geneontology.org/R-HSA-1059683>
        a       <http://www.w3.org/2002/07/owl#Ontology> ;
        <http://geneontology.org/lego/modelstate>
                "development" ;
        <http://purl.org/dc/elements/1.1/contributor>
                "https://reactome.org/content/detail/R-HSA-1059683" ;
        <http://purl.org/dc/elements/1.1/date>
                "2020-03-31" ;
        <http://purl.org/dc/elements/1.1/title>
                "Reactome:unexpanded:Interleukin-6 signaling" ;
        <http://purl.org/pav/providedBy>
                "https://reactome.org" ;
        <http://www.w3.org/2002/07/owl#imports>
                <http://purl.obolibrary.org/obo/go/extensions/go-lego.owl> ;
        <https://w3id.org/biolink/vocab/in_taxon>
                "http://purl.obolibrary.org/obo/NCBITaxon_9606" .
```

**Comment by dustine32** [comment]
Can do @goodb! How do you currently (or plan to) source the taxon given a gene ID? Is it a GOlr call, or SPARQL query to some RDF store?

**Comment by goodb** [comment]
For you.. I'd suggest just putting it in as a parameter when you run e.g. a 'mouse' import as it will usually be the same.  Unless we have some weird cross-species model.  

I have a minerva-cli command that will take a journal of go-cams and use the neo ontology to figure it out and add it.

**Comment by dustine32** [comment]
Right @goodb, I don't need to complicate it right now, just tie `NCBITaxon:6239` to WB load and `NCBITaxon:10090` to MGI load.

I figured it should be this simple but then recalled that some of the MGI GPAD `with/from` field values will be to human genes. But then these might not actually get translated to OWL individuals if they are on non-binding annotations. So might not be an issue. But if it is we can get fancy further down the road.

**Comment by dustine32** [comment]
@kltm suggested I pull taxon from the MGI/WB GPI file. Since the context here is already centered around GPAD/GPI this should be real slick and easy.

**Comment by dustine32** [comment]
Taxon ID is reliably being added to models now.
