### ISSUE TITLE
Add date and contributor to ALL annotation individuals? Not just evidence and Axiom?

### ISSUE THREAD

**Issue by dustine32** [geneontology/gocamgen#86]
I looked at where I'm adding the date and contributor in the OWL and it's actually only going on the evidence individual and Axiom. [For example](http://noctua-dev.berkeleybop.org/editor/graph/gomodel:MGI_MGI_1929608?):
```
<http://model.geneontology.org/MGI_MGI_1929608/883a11ec-3dfc-4fa3-9360-e1ad750b9178> rdf:type owl:NamedIndividual ,
                              <http://purl.obolibrary.org/obo/ECO_0000314> ;
                     <http://purl.org/dc/elements/1.1/contributor> "http://orcid.org/0000-0002-9796-7693" ;
                     <http://purl.org/dc/elements/1.1/date> "2004-04-30" ;
                     <http://purl.org/dc/elements/1.1/source> "PMID:14627703" .

[ rdf:type owl:Axiom ;
   owl:annotatedSource <http://model.geneontology.org/MGI_MGI_1929608/b3ffd04a-8812-4828-9585-85149d8d92fb> ;  # GO:0003674 individual
   owl:annotatedProperty <http://purl.obolibrary.org/obo/RO_0002333> ;  # enabled_by
   owl:annotatedTarget <http://model.geneontology.org/MGI_MGI_1929608/0bf87fe2-bc66-4f35-90c4-c0780329b28a> ;  # MGI:MGI:1929608 individual
   <http://geneontology.org/lego/evidence> <http://model.geneontology.org/MGI_MGI_1929608/883a11ec-3dfc-4fa3-9360-e1ad750b9178> ;
   <http://purl.org/dc/elements/1.1/contributor> "http://orcid.org/0000-0002-9796-7693" ;
   <http://purl.org/dc/elements/1.1/date> "2004-04-30" ;
   rdfs:comment "MGI:MGI:1929608  RO:0002264 GO:0042985 MGI:MGI:3028747|PMID:14627703 ECO:0000314   2004-04-30 MGI  creation-date=2004-04-30|modification-date=2004-04-30|contributor-id=http://orcid.org/0000-0002-9796-7693"
 ] .
```
(The evidence individual started getting these fields in response to https://github.com/geneontology/gocamgen/issues/15)

Meanwhile, the GP and term individuals aren't currently getting any contributor or date. Should I start doing this? This might get cluttered when "collapsing" (translating) multiple GPAD lines to single annotation individuals, like what is currently happening to cause the multiple dates seen [here](http://noctua-dev.berkeleybop.org/editor/graph/gomodel:MGI_MGI_88451?):
![image](https://user-images.githubusercontent.com/2678599/106952249-b7ac5300-66e5-11eb-8013-780e4766eaa4.png)

Tagging @kltm @ukemi @vanaukenk. We can close if no action is needed.

**Comment by kltm** [comment]
@dustine32 I'm not sure if we discussed this elsewhere, but date and contributor must exist on all individuals and at the model level.

**Comment by dustine32** [comment]
@kltm Thanks for clarifying this! I will update in the code.

**Comment by kltm** [comment]
@dustine32 Actually, have you tried the ShEx on these yet? I would hope that they would have failed for this reason; if not, that's another thing to worry about...

**Comment by dustine32** [comment]
This looks to be working stably in all of the new models.
