### ISSUE TITLE
Emit comment in annotation properties

### ISSUE THREAD

**Issue by dustine32** [geneontology/gocamgen#87]
Given one or more `comment=` values in an annotation's properties field, emit these somewhere on the assertion. In a first pass at this I added it just to the evidence individual:
![image](https://user-images.githubusercontent.com/2678599/110715039-53cfeb00-81b9-11eb-89f6-69d043154bea.png)
Note how the assertion's edge/axiom "comment" (the original source line) at the bottom is separate from the evidence individual at the top.

@ukemi @vanaukenk @sabrinatoro Is this an OK solution?

**Comment by ukemi** [comment]
This is exactly correct for the MGI annotations. The comments go with each individual annotation and therefore 'go' with the evidence statement. These will only be imported once and will not be emitted in the public GPAD. 

What I hope to do in the future is be able to search these as I build more complicated models. They often contain tidbits of information that will help a lot when we want to build models in a specific context. This will be particularly useful where I have captured participants in legacy annotations but was unable to capture exactly how those participants related to the core annotation.
