### ISSUE TITLE
Add gene symbol to model title

### ISSUE THREAD

**Issue by dustine32** [geneontology/gocamgen#90]
Currently, model titles are simply the gene identifier. E.g. "MGI:MGI:95290":
![image](https://user-images.githubusercontent.com/2678599/117345556-89aceb00-ae5b-11eb-8e08-e4c64ec0819b.png)

To help with readability, we should add the gene symbol to the title. Suggested format:
```
{GeneID}, {GeneSymbol}
MGI:MGI:95290, Egf
```
Symbol will be grabbed from GPI. Should we worry about the case where a symbol doesn't exist for a gene?

Tagging @vanaukenk @ukemi

**Comment by ukemi** [comment]
How about also tagging that it is a 'gene-centric' model too?

**Comment by dustine32** [comment]
@ukemi Great idea! I'm guessing that tag should be incorporated into the title? So the above example model should be titled: "MGI:MGI:95290, Egf (gene-centric)"

Again, format suggestions very much welcome!

Or would it be worth it to create a new field, similar to `modelstate`? Maybe a new field is too much?

**Comment by tmushayahama** [comment]
I think we have to revisit the title naming guidelines across all models. There are a few tickets and discussions for this issue. One ticket I can think of is this one and Ben's comment. https://github.com/geneontology/noctua-form/issues/36

But my thoughts is to avoid dynamic/variable title names. If one changes GP name, or Reference let's say bulk edit, will they remember to change the title name as well.

Tagging @ukemi @vanaukenk @lpalbou

**Comment by dustine32** [comment]
@tmushayahama Ohhh yeah... Like if a gene symbol is changed at the MOD and a year later someone points out that the model title is wrong? Though I suppose manually correcting a model title in Noctua when you notice it is pretty easy.

**Comment by ukemi** [comment]
I think that was the motivation for having the ID there. Gene symbols change and and IDs never change.

**Comment by dustine32** [comment]
New format suggestion from @ukemi:
> How about ‘Egf (MGI:MGI:95290)- gene centric model’ as the title with the caveat that the gene symbol may change and be incorrect in the future?

So now the pattern will be:
```
{GeneSymbol} ({GeneID})- gene centric model
```

**Comment by tmushayahama** [comment]
@dustine32 @ukemi @vanaukenk from comment above (gene symbols change), I was thinking the first format was great? 

`{GeneID} - {GeneSymbol} - gene centric`

Since the symbol is supplementing the already ID and (in case the label is too long or missing). Title search also match from the left for some reasons :) 

Also will this apply to ZFIN models as well for consistence?

@dustine32 I think @lpalbou  will be interested in this new field thing you mentioned for genecentric, processcentric etc

**Comment by ukemi** [comment]
Any of this works for me as long as the ID is there.

**Comment by ukemi** [comment]
I'm still a bit confused about the relationships between models. if I create a process-process centric model, will I be expected to create a duplicate annotations that are the derivations of the ones from the process-centric model in the gene-centric model? I think it would be good to consider how to handle this sooner rather than later.

**Comment by vanaukenk** [comment]
@ukemi 
Agreed, but I think that is a separate issue and if we don't already have it, we should start a Google doc where we can record things like this so we don't lose track of these SOP-type decisions and workflows we need to make.

**Comment by dustine32** [comment]
Ok, I'm going to baby-step this into the code used to make the next load, with the intersection of the patterns:
```
hlh-1 (WB:WBGene00001948)
```
Of course, we can change this in a later test load.

**Comment by ukemi** [comment]
Hi @dustine. I looked at the MGI models on dev and this looks like it worked. @vanaukenk if this worked for the worm models, I think we can close this.

**Comment by vanaukenk** [comment]
@dustine32 @ukemi 
For the WB imports, any of the genes that *are* in our current gpi file, i.e. ncRNAs, loaded fine, so I think we can close this issue.
However, we still have the issue that the updated WB gpi file with uncloned loci is not at the GOC yet, but I think that's a separate issue.
