### ISSUE TITLE
Set import model states to production so annotations are in GPAD outputs from dev

### ISSUE THREAD

**Issue by ukemi** [geneontology/gocamgen#93]
The next step in the annotation round-tripping project is to generate a GPAD file that curators can quality-control check and that can subsequently be used as a test load into the MOD resources: https://github.com/geneontology/pipeline/issues/237

In order to do this in the current dev environment, we will need to set the model state to production so annotations are generated from the imported models. This may impinge on: #91 

@dustine32 I think this will require a reload?

ping @vanaukenk

**Comment by vanaukenk** [comment]
@dustine32 @ukemi @kltm 

Any reason not to default imported models on noctua-dev to status 'production' so that the noctua-dev pipeline will start producing a GPAD output as soon as models start coming in?

If we have a full 'pipeline' set up on noctua-dev from the start it would provide a good opportunity to catch issues with the GPAD export that might best be handled upstream in the import code.

**Comment by kltm** [comment]
`dev` is a complete playground, so whatever is useful to test can be done there. 
As we get closer in a final switchover, we will want to have a separate branch of noctua-models that is more-or-less the current `master` of noctua-models plus the WB models in their final state, including being set to "production"--this will be the branch that will be the final PR when things are switched on as the final step. If you want to test that earlier on on noctua-dev, that's totally doable and fine.

**Comment by dustine32** [comment]
@ukemi Sure, after I take a few minutes to implement #91 a reload would be the easiest way to set these all to `production`. I know @sierra-moxon also bulk updated status of the ZFIN models (maybe through pattern-matching with a `sed` command?), but it's about time to make this status thing easier.

**Comment by dustine32** [comment]
@ukemi Looks like we're getting the import annotations back out from Noctua in the `noctua_mgi.gpad` available here:
http://skyhook.berkeleybop.org/issue-237-mgi-test-pipeline/products/annotations/noctua_mgi.gpad.gz

For this ticket specifically, I see the `model-state` coming out for these as `production`:
```
MGI     MGI:101757      acts_upstream_of_or_within      GO:0001842      PMID:15649475   ECO:0000315
     MGI:MGI:3574399         20050511        MGI             noctua-model-id=gomodel:MGI_MGI_101757|contributor=http://orcid.org/0000-0001-7476-6306|model-state=production
```
So, I'm gonna close this ticket for now but feel free to reopen as needed.

**Comment by ukemi** [comment]
Awesome!!!!!! We will start our QC.
